In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import unidecode
import time

from openpyxl import load_workbook
#import basedosdados as bd

pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Queremos as seguintes colunas:

* MUNICIPIO 
* NOME_PARTIDO
* NOHOMENS 
* NOMULHERES 
* TOTAL 
* PERCENTDASVAGASDISPONIVEIS (porcentagem de candidatos que o partido ou coligação lançou em cada eleição)
* NUMERODEVAGASDISPONIVEIS

Todos os dados com as candidaturas dos anos 2014 e 2018 foram retirados daqui: https://www.tse.jus.br/hotsites/pesquisas-eleitorais/candidatos.html

# Deputados Estaduais

## 2014 (com e sem coligação)

In [2]:
path = 'consulta_cand_2014/consulta_cand_2014_BRASIL.csv'
df_2014 = pd.read_csv(path, sep=';', encoding='latin1', low_memory=False, decimal=',')

df_2014.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_CARGO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,NM_URNA_CANDIDATO,NM_SOCIAL_CANDIDATO,NR_CPF_CANDIDATO,NM_EMAIL,CD_SITUACAO_CANDIDATURA,DS_SITUACAO_CANDIDATURA,CD_DETALHE_SITUACAO_CAND,DS_DETALHE_SITUACAO_CAND,TP_AGREMIACAO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,CD_NACIONALIDADE,DS_NACIONALIDADE,SG_UF_NASCIMENTO,CD_MUNICIPIO_NASCIMENTO,NM_MUNICIPIO_NASCIMENTO,DT_NASCIMENTO,NR_IDADE_DATA_POSSE,NR_TITULO_ELEITORAL_CANDIDATO,CD_GENERO,DS_GENERO,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,VR_DESPESA_MAX_CAMPANHA,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,ST_REELEICAO,ST_DECLARAR_BENS,NR_PROTOCOLO_CANDIDATURA,NR_PROCESSO,CD_SITUACAO_CANDIDATO_PLEITO,DS_SITUACAO_CANDIDATO_PLEITO,CD_SITUACAO_CANDIDATO_URNA,DS_SITUACAO_CANDIDATO_URNA,ST_CANDIDATO_INSERIDO_URNA
0,08/04/2021,11:38:59,2014,2,ELEIÇÃO ORDINÁRIA,1,143,Eleições Gerais 2014,05/10/2014,FEDERAL,RJ,RJ,RIO DE JANEIRO,7,DEPUTADO ESTADUAL,190000003276,13819,JAQUELINE MARQUES TEIXEIRA,JAQUELINE MARQUES,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,13,PT,PARTIDO DOS TRABALHADORES,190000000010,PARTIDO ISOLADO,PT,-4,NÃO DIVULGÁVEL,Não divulgável,-3,NÃO DIVULGÁVEL,NaN,nan,-4,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,5,SUPLENTE,Não divulgável,Não divulgável,1047852014,37404120146190000,2,DEFERIDO,2,DEFERIDO,SIM
1,08/04/2021,11:38:25,2014,2,ELEIÇÃO ORDINÁRIA,1,143,Eleições Gerais 2014,05/10/2014,FEDERAL,AC,AC,ACRE,7,DEPUTADO ESTADUAL,10000000131,65565,LUZIELE ALVES DIAS,LUZIELE,#NULO#,19682140200,PCDOBACRI@GMAIL.COM,12,APTO,2,DEFERIDO,COLIGAÇÃO,65,PC do B,PARTIDO COMUNISTA DO BRASIL,10000000024,FRENTE POPULAR DO ACRE VI,PC do B / PTB,1,BRASILEIRA NATA,AC,-3,RIO BRANCO,06/05/1970,44.00,1743942453,4,FEMININO,8,SUPERIOR COMPLETO,3,CASADO(A),3,PARDA,266,PROFESSOR DE ENSINO MÉDIO,600000,5,SUPLENTE,N,S,52882014,1981620146010000,2,DEFERIDO,2,DEFERIDO,SIM
2,08/04/2021,11:38:25,2014,2,ELEIÇÃO ORDINÁRIA,1,143,Eleições Gerais 2014,05/10/2014,FEDERAL,RS,RS,RIO GRANDE DO SUL,6,DEPUTADO FEDERAL,210000000667,4567,LEUDO IRAJA SANTOS COSTA,LEUDO COSTA,#NULO#,20529457091,LEUDOCOSTA@MEIOAMBIENTELEGAL.COM.BR,12,APTO,2,DEFERIDO,COLIGAÇÃO,45,PSDB,PARTIDO DA SOCIAL DEMOCRACIA BRASILEIRA,210000000020,UNIDOS PELA ESPERANÇA,PP / PRB / SD / PSDB,1,BRASILEIRA NATA,RS,-3,SANTIAGO,19/10/1955,59.00,37851190450,2,MASCULINO,8,SUPERIOR COMPLETO,9,DIVORCIADO(A),1,BRANCA,131,ADVOGADO,4500000,5,SUPLENTE,N,S,315182014,5147120146210000,2,DEFERIDO,2,DEFERIDO,SIM
3,08/04/2021,11:38:25,2014,2,ELEIÇÃO ORDINÁRIA,1,143,Eleições Gerais 2014,05/10/2014,FEDERAL,GO,GO,GOIÁS,7,DEPUTADO ESTADUAL,90000000500,50111,ARNALDO LUIZ DA SILVA,ARNALDINHO,#NULO#,49062948120,SOLANOCASTRO50@GMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,50,PSOL,PARTIDO SOCIALISMO E LIBERDADE,90000000021,PARTIDO ISOLADO,PSOL,1,BRASILEIRA NATA,PE,-3,SAO BEBEDITO DO SUL,31/07/1964,50.00,39479221066,2,MASCULINO,3,ENSINO FUNDAMENTAL INCOMPLETO,1,SOLTEIRO(A),3,PARDA,999,OUTROS,200000,4,NÃO ELEITO,N,S,303612014,7627020146090000,2,DEFERIDO,2,DEFERIDO,SIM
4,08/04/2021,11:38:25,2014,2,ELEIÇÃO ORDINÁRIA,1,143,Eleições Gerais 2014,05/10/2014,FEDERAL,RJ,RJ,RIO DE JANEIRO,7,DEPUTADO ESTADUAL,190000000746,70038,JOSÉ JAILSON CRUZ,CAMARÃO,#NULO#,39653501704,JAILSONJCRUZ@IG.COM.BR,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,70,PT do B,PARTIDO TRABALHISTA DO BRASIL,190000000015,PARTIDO ISOLADO,PT do B,1,BRASILEIRA NATA,AL,-3,PENEDO,28/08/1952,62.00,49091390353,2,MASCULINO,7,SUPERIOR INCOMPLETO,3,CASADO(A),1,BRANCA,999,OUTROS,1000000,5,SUPLENTE,N,N,759262014,27392120146190000,2,DEFERIDO,2,DEFERIDO,SIM

In [3]:
df_2014.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'NR_CPF_CANDIDATO', 'NM_EMAIL',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND', 'TP_AGREMIACAO',
       'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO', 'SQ_COLIGACAO',
       'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO', 'CD_NACIONALIDADE',
       'DS_NACIONALIDADE', 'SG_UF_NASCIMENTO', 'CD_MUNICIPIO_NASCIMENTO',
       'NM_MUNICIPIO_NASCIMENTO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE',
       'NR_TITULO_ELEITORAL_CANDIDATO', 'CD_GENERO', 'DS_GENERO',
       'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO', 'CD_ESTADO_CIVIL',
       'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA', 'CD_OCUPACAO',
       'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA', 'CD_SIT_TOT_TURNO',
       'DS_SIT_TOT_TURNO', 'ST_REELEICAO', 'ST_DECLARAR_BENS',
       'NR_PROTOCOLO_CANDIDATURA', 'NR_PROCESSO',
       'CD_SITUACAO_CANDIDATO_PLEITO', 'DS_SITUACAO_CANDIDATO_PLEITO',
       'CD_SITUACAO_CANDIDATO_URNA', 'DS_SITUACAO_CANDIDATO_URNA',
       'ST_CANDIDATO_INSERIDO_URNA'],
      dtype='object')

### Vagas disponíveis para deputados estaduais por estado em 2014

Os dados de vagas obtidos em: https://www.tse.jus.br/eleicoes/estatisticas/estatisticas-eleitorais estavam incorretos. A seguir os sites onde é possível obter a informação de vagas disponíveis para alguns estados:

Tocantins: 24 http://g1.globo.com/to/tocantins/eleicoes/2014/noticia/2014/10/saiba-quais-sao-coligacoes-e-os-partidos-nas-eleicoes-para-deputados.html
Goais: 41 https://www.tre-go.jus.br/eleicoes/eleicoes-anteriores/eleicoes-2014/registro-de-candidaturas-2014

Santa Catarina: 40 https://apps.tre-sc.jus.br/site/eleicoes/eleicoes-2014/resultado-1o-turno/index.html

Paraná: 54 https://mppr.mp.br/modules/conteudo/conteudo.php?conteudo=5745

Para acessá-los basta selecionar quais os dados de interesse e fazer o download do arquivo na página tabelas detalhadas abaixo do título CANDIDATOS(AS) POR VAGA.

Vagas para deputado estadual por estado: 

“O número de Deputados à Assembleia Legislativa corresponderá ao triplo da representação do Estado na Câmara dos Deputados e, atingido o número de trinta e seis, será acrescido de tantos quantos forem os Deputados Federais acima de doze”, diz o artigo 27 da Constituição federal.

#### Acabei por utilizar para vagas os dados de 2018 (supondo que a quantidade de vagas permanceu igual nas duas eleições).

In [4]:
df_vagas_2014 = pd.read_csv('relacao_vaga_2018.csv', sep=';', encoding='latin1', low_memory=False, usecols=['UF','Cargo', 'Quantitativo', 'Vaga'])

df_deputados_estaduais_2014 = df_vagas_2014[df_vagas_2014['Cargo'] == 'Deputado Estadual']

df_deputados_estaduais_2014 = df_deputados_estaduais_2014.rename(columns={'UF': 'SG_UF', 'Vaga': 'VAGAS'});

In [5]:
df_deputados_estaduais_2014

    SG_UF              Cargo  Quantitativo  VAGAS
110    AC  Deputado Estadual           471     24
111    AL  Deputado Estadual           336     27
112    AM  Deputado Estadual           657     24
113    AP  Deputado Estadual           495     24
114    BA  Deputado Estadual           643     63
115    CE  Deputado Estadual           597     46
116    ES  Deputado Estadual           614     30
117    GO  Deputado Estadual           907     41
118    MA  Deputado Estadual           535     42
119    MG  Deputado Estadual          1382     77
120    MS  Deputado Estadual           355     24
121    MT  Deputado Estadual           350     24
122    PA  Deputado Estadual           692     41
123    PB  Deputado Estadual           429     36
124    PE  Deputado Estadual           681     49
125    PI  Deputado Estadual           219     30
126    PR  Deputado Estadual           767     54
127    RJ  Deputado Estadual          2465     70
128    RN  Deputado Estadual           330     24
129    RO  Deputado Estadual           466     24
130    RR  Deputado Estadual           485     24
131    RS  Deputado Estadual           853     55
132    SC  Deputado Estadual           469     40
133    SE  Deputado Estadual           335     24
134    SP  Deputado Estadual          2174     94
135    TO  Deputado Estadual           234     24

### Candidatos a deputados estaduais em 2014

Abaixo estão as coligações presentes em cada estado e a quantidade de candidaturas por gênero em cada coligação, além da quantidade de candidaturas por gênero representadas por partidos isolados:

### Deputados estaduais com coligação

Respostas para o campo de 'DS_GENERO':

In [6]:
df_2014['DS_GENERO'].unique()

array(['NÃO DIVULGÁVEL', 'FEMININO', 'MASCULINO'], dtype=object)

Gênero Feminino

In [7]:
df_deputado_estadual_com_coligacao_genero_feminino_2014 = df_2014[
    (df_2014['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2014['DS_GENERO'] == 'FEMININO') &
    (df_2014['TP_AGREMIACAO'] == 'COLIGAÇÃO') &
    (df_2014['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()

In [8]:
df_deputado_estadual_com_coligacao_genero_feminino_2014 = df_deputado_estadual_com_coligacao_genero_feminino_2014.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [9]:
df_deputado_estadual_com_coligacao_genero_feminino_2014.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_FEMININO
0,AC,ACRE,10000000024,FRENTE POPULAR DO ACRE VI,5
1,AC,ACRE,10000000028,FRENTE POPULAR DO ACRE 5,12
2,AC,ACRE,10000000029,Frente Trabalhista Republicana Humanista Livre,20
3,AC,ACRE,10000000031,PRODUZIR PARA EMPREGAR,18
4,AC,ACRE,10000000032,FRENTE SOCIAL LIBERAL DEMOCRATA CRISTÃ,9

Gênero Masculino

In [10]:
df_deputado_estadual_com_coligacao_genero_masculino_2014 = df_2014[
    (df_2014['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2014['DS_GENERO'] == 'MASCULINO') &
    (df_2014['TP_AGREMIACAO'] == 'COLIGAÇÃO') &
    (df_2014['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()

In [11]:
df_deputado_estadual_com_coligacao_genero_masculino_2014 = df_deputado_estadual_com_coligacao_genero_masculino_2014.rename(columns={'DS_GENERO':'GENERO_MASCULINO'});

In [12]:
df_deputado_estadual_com_coligacao_genero_masculino_2014.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_MASCULINO
0,AC,ACRE,10000000024,FRENTE POPULAR DO ACRE VI,11
1,AC,ACRE,10000000028,FRENTE POPULAR DO ACRE 5,23
2,AC,ACRE,10000000029,Frente Trabalhista Republicana Humanista Livre,46
3,AC,ACRE,10000000031,PRODUZIR PARA EMPREGAR,39
4,AC,ACRE,10000000032,FRENTE SOCIAL LIBERAL DEMOCRATA CRISTÃ,22

Genêro não divulgável

In [13]:
df_deputado_estadual_com_coligacao_nao_divulgavel_2014 = df_2014[
    (df_2014['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2014['DS_GENERO'] == 'NÃO DIVULGÁVEL') &
    (df_2014['TP_AGREMIACAO'] == 'COLIGAÇÃO') &
    (df_2014['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()
df_deputado_estadual_com_coligacao_nao_divulgavel_2014 = df_deputado_estadual_com_coligacao_nao_divulgavel_2014.rename(columns={'DS_GENERO':'GENERO_NAO_DIV'});

In [14]:
df_deputado_estadual_com_coligacao_nao_divulgavel_2014.head()

  SG_UF    NM_UE  SQ_COLIGACAO          NM_COLIGACAO  GENERO_NAO_DIV
0    PR   PARANÁ  160000000007         Avança Paraná               1
1    RR  RORAIMA  230000000019  TRABALHO E PROGRESSO               1

Colocando os resultados numa mesma tabela:

In [15]:
df_deputado_estadual_com_coligacao_por_genero_2014 = pd.merge(pd.merge(df_deputado_estadual_com_coligacao_genero_feminino_2014, df_deputado_estadual_com_coligacao_genero_masculino_2014[['SQ_COLIGACAO', 'GENERO_MASCULINO']], on = 'SQ_COLIGACAO', how = 'outer'), df_deputado_estadual_com_coligacao_nao_divulgavel_2014[['SQ_COLIGACAO', 'GENERO_NAO_DIV']], on = 'SQ_COLIGACAO', how = 'outer') 
df_deputado_estadual_com_coligacao_por_genero_2014 = df_deputado_estadual_com_coligacao_por_genero_2014.fillna(0)

In [16]:
df_deputado_estadual_com_coligacao_por_genero_2014.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_FEMININO,GENERO_MASCULINO,GENERO_NAO_DIV
0,AC,ACRE,10000000024,FRENTE POPULAR DO ACRE VI,5.00,11,0.00
1,AC,ACRE,10000000028,FRENTE POPULAR DO ACRE 5,12.00,23,0.00
2,AC,ACRE,10000000029,Frente Trabalhista Republicana Humanista Livre,20.00,46,0.00
3,AC,ACRE,10000000031,PRODUZIR PARA EMPREGAR,18.00,39,0.00
4,AC,ACRE,10000000032,FRENTE SOCIAL LIBERAL DEMOCRATA CRISTÃ,9.00,22,0.00

Total de candidatos por coligação por município:

In [17]:
df_deputado_estadual_com_coligacao_por_genero_2014['TOTAL'] = df_deputado_estadual_com_coligacao_por_genero_2014['GENERO_FEMININO'] + df_deputado_estadual_com_coligacao_por_genero_2014['GENERO_MASCULINO'] + df_deputado_estadual_com_coligacao_por_genero_2014['GENERO_NAO_DIV']

Porcentagem de candidatos por gênero

In [18]:
df_deputado_estadual_com_coligacao_por_genero_2014['PERC_FEM'] = (df_deputado_estadual_com_coligacao_por_genero_2014['GENERO_FEMININO']/df_deputado_estadual_com_coligacao_por_genero_2014['TOTAL'])*100
df_deputado_estadual_com_coligacao_por_genero_2014['PERC_MASC'] = (df_deputado_estadual_com_coligacao_por_genero_2014['GENERO_MASCULINO']/df_deputado_estadual_com_coligacao_por_genero_2014['TOTAL'])*100
df_deputado_estadual_com_coligacao_por_genero_2014['PERC_NAO_DIV'] = (df_deputado_estadual_com_coligacao_por_genero_2014['GENERO_NAO_DIV']/df_deputado_estadual_com_coligacao_por_genero_2014['TOTAL'])*100

In [19]:
df_deputado_estadual_com_coligacao_por_genero_2014 = pd.merge(df_deputado_estadual_com_coligacao_por_genero_2014, df_deputados_estaduais_2014[['SG_UF', 'VAGAS']] , on = 'SG_UF')

In [20]:
df_deputado_estadual_com_coligacao_por_genero_2014['PERCENT_OCUPADO'] = (df_deputado_estadual_com_coligacao_por_genero_2014['TOTAL']/df_deputado_estadual_com_coligacao_por_genero_2014['VAGAS'])*100

In [21]:
df_deputado_estadual_com_coligacao_por_genero_2014.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_FEMININO,GENERO_MASCULINO,GENERO_NAO_DIV,TOTAL,PERC_FEM,PERC_MASC,PERC_NAO_DIV,VAGAS,PERCENT_OCUPADO
0,AC,ACRE,10000000024,FRENTE POPULAR DO ACRE VI,5.00,11,0.00,16.00,31.25,68.75,0.00,24,66.67
1,AC,ACRE,10000000028,FRENTE POPULAR DO ACRE 5,12.00,23,0.00,35.00,34.29,65.71,0.00,24,145.83
2,AC,ACRE,10000000029,Frente Trabalhista Republicana Humanista Livre,20.00,46,0.00,66.00,30.30,69.70,0.00,24,275.00
3,AC,ACRE,10000000031,PRODUZIR PARA EMPREGAR,18.00,39,0.00,57.00,31.58,68.42,0.00,24,237.50
4,AC,ACRE,10000000032,FRENTE SOCIAL LIBERAL DEMOCRATA CRISTÃ,9.00,22,0.00,31.00,29.03,70.97,0.00,24,129.17

### Deputados estaduais sem coligação

In [22]:
df_deputado_estadual_sem_coligacoes_genero_feminino_2014 = df_2014[
    (df_2014['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2014['DS_GENERO'] == 'FEMININO') &
    (df_2014['TP_AGREMIACAO'] == 'PARTIDO ISOLADO') &
    (df_2014['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NR_PARTIDO', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()
df_deputado_estadual_sem_coligacoes_genero_feminino_2014 = df_deputado_estadual_sem_coligacoes_genero_feminino_2014.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [23]:
df_deputado_estadual_sem_coligacoes_genero_feminino_2014.head()

  SG_UF NM_UE  SQ_COLIGACAO  NR_PARTIDO SG_PARTIDO  GENERO_FEMININO
0    AC  ACRE   10000000021          12        PDT               11
1    AC  ACRE   10000000022          55        PSD                8
2    AC  ACRE   10000000023          44        PRP               11
3    AC  ACRE   10000000025          50       PSOL                3
4    AC  ACRE   10000000030          11         PP                7

In [24]:
df_deputado_estadual_sem_coligacoes_genero_masculino_2014 = df_2014[
    (df_2014['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2014['DS_GENERO'] == 'MASCULINO') &
    (df_2014['TP_AGREMIACAO'] == 'PARTIDO ISOLADO') &
    (df_2014['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO','NR_PARTIDO', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()
df_deputado_estadual_sem_coligacoes_genero_masculino_2014 = df_deputado_estadual_sem_coligacoes_genero_masculino_2014.rename(columns={'DS_GENERO':'GENERO_MASCULINO'});

In [25]:
df_deputado_estadual_sem_coligacoes_genero_masculino_2014.head()

  SG_UF NM_UE  SQ_COLIGACAO  NR_PARTIDO SG_PARTIDO  GENERO_MASCULINO
0    AC  ACRE   10000000021          12        PDT                24
1    AC  ACRE   10000000022          55        PSD                16
2    AC  ACRE   10000000023          44        PRP                24
3    AC  ACRE   10000000025          50       PSOL                 7
4    AC  ACRE   10000000030          11         PP                27

In [26]:
df_deputado_estadual_sem_coligacoes_nao_divulgavel_2014 = df_2014[
    (df_2014['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2014['DS_GENERO'] == 'NÃO DIVULGÁVEL') &
    (df_2014['TP_AGREMIACAO'] == 'PARTIDO ISOLADO') &
    (df_2014['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NR_PARTIDO', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()
df_deputado_estadual_sem_coligacoes_nao_divulgavel_2014 = df_deputado_estadual_sem_coligacoes_nao_divulgavel_2014.rename(columns={'DS_GENERO':'GENERO_NAO_DIV'});

In [27]:
df_deputado_estadual_sem_coligacoes_nao_divulgavel_2014

,SG_UF,NM_UE,SQ_COLIGACAO,NR_PARTIDO,SG_PARTIDO,GENERO_NAO_DIV
0,RJ,RIO DE JANEIRO,190000000010,13,PT,2
1,RJ,RIO DE JANEIRO,190000000023,65,PC do B,3
2,RS,RIO GRANDE DO SUL,210000000011,13,PT,1

Nesse caso há alguns partidos que só possuem candidaturas femininas ou masculinas.

In [28]:
df_deputado_estadual_sem_coligacoes_por_genero_2014 = pd.merge(pd.merge(df_deputado_estadual_sem_coligacoes_genero_masculino_2014, df_deputado_estadual_sem_coligacoes_genero_feminino_2014, on = ['SG_UF', 'NM_UE','SQ_COLIGACAO', 'SG_PARTIDO', 'NR_PARTIDO'], how = 'outer'), df_deputado_estadual_sem_coligacoes_nao_divulgavel_2014[['SQ_COLIGACAO', 'GENERO_NAO_DIV']], on = 'SQ_COLIGACAO', how= 'outer')
df_deputado_estadual_sem_coligacoes_por_genero_2014 = df_deputado_estadual_sem_coligacoes_por_genero_2014.fillna(0)

In [29]:
df_deputado_estadual_sem_coligacoes_por_genero_2014.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NR_PARTIDO,SG_PARTIDO,GENERO_MASCULINO,GENERO_FEMININO,GENERO_NAO_DIV
0,AC,ACRE,10000000021,12,PDT,24.00,11.00,0.00
1,AC,ACRE,10000000022,55,PSD,16.00,8.00,0.00
2,AC,ACRE,10000000023,44,PRP,24.00,11.00,0.00
3,AC,ACRE,10000000025,50,PSOL,7.00,3.00,0.00
4,AC,ACRE,10000000030,11,PP,27.00,7.00,0.00

In [30]:
df_deputado_estadual_sem_coligacoes_por_genero_2014['TOTAL'] = df_deputado_estadual_sem_coligacoes_por_genero_2014['GENERO_FEMININO'] + df_deputado_estadual_sem_coligacoes_por_genero_2014['GENERO_MASCULINO'] + df_deputado_estadual_sem_coligacoes_por_genero_2014['GENERO_NAO_DIV']
df_deputado_estadual_sem_coligacoes_por_genero_2014['PERC_FEM'] = (df_deputado_estadual_sem_coligacoes_por_genero_2014['GENERO_FEMININO']/df_deputado_estadual_sem_coligacoes_por_genero_2014['TOTAL'])*100
df_deputado_estadual_sem_coligacoes_por_genero_2014['PERC_MASC'] = (df_deputado_estadual_sem_coligacoes_por_genero_2014['GENERO_MASCULINO']/df_deputado_estadual_sem_coligacoes_por_genero_2014['TOTAL'])*100
df_deputado_estadual_sem_coligacoes_por_genero_2014['PERC_NAO_DIV'] = (df_deputado_estadual_sem_coligacoes_por_genero_2014['GENERO_NAO_DIV']/df_deputado_estadual_sem_coligacoes_por_genero_2014['TOTAL'])*100

In [31]:
df_deputado_estadual_sem_coligacoes_por_genero_2014 = pd.merge(df_deputado_estadual_sem_coligacoes_por_genero_2014, df_deputados_estaduais_2014[['SG_UF', 'VAGAS']] , on = 'SG_UF', how = 'outer')

In [32]:
df_deputado_estadual_sem_coligacoes_por_genero_2014['PERCENT_OCUPADO'] = (df_deputado_estadual_sem_coligacoes_por_genero_2014['TOTAL']/df_deputado_estadual_sem_coligacoes_por_genero_2014['VAGAS'])*100

In [33]:
df_deputado_estadual_sem_coligacoes_por_genero_2014.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NR_PARTIDO,SG_PARTIDO,GENERO_MASCULINO,GENERO_FEMININO,GENERO_NAO_DIV,TOTAL,PERC_FEM,PERC_MASC,PERC_NAO_DIV,VAGAS,PERCENT_OCUPADO
0,AC,ACRE,10000000021,12,PDT,24.00,11.00,0.00,35.00,31.43,68.57,0.00,24,145.83
1,AC,ACRE,10000000022,55,PSD,16.00,8.00,0.00,24.00,33.33,66.67,0.00,24,100.00
2,AC,ACRE,10000000023,44,PRP,24.00,11.00,0.00,35.00,31.43,68.57,0.00,24,145.83
3,AC,ACRE,10000000025,50,PSOL,7.00,3.00,0.00,10.00,30.00,70.00,0.00,24,41.67
4,AC,ACRE,10000000030,11,PP,27.00,7.00,0.00,34.00,20.59,79.41,0.00,24,141.67

## 2018 (com e sem coligação)

In [34]:
path = 'consulta_cand_2018/consulta_cand_2018_BRASIL.csv'
df_2018 = pd.read_csv(path, sep=';', encoding='latin1', low_memory=False, decimal=',')

df_2018.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_CARGO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,NM_URNA_CANDIDATO,NM_SOCIAL_CANDIDATO,NR_CPF_CANDIDATO,NM_EMAIL,CD_SITUACAO_CANDIDATURA,DS_SITUACAO_CANDIDATURA,CD_DETALHE_SITUACAO_CAND,DS_DETALHE_SITUACAO_CAND,TP_AGREMIACAO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,CD_NACIONALIDADE,DS_NACIONALIDADE,SG_UF_NASCIMENTO,CD_MUNICIPIO_NASCIMENTO,NM_MUNICIPIO_NASCIMENTO,DT_NASCIMENTO,NR_IDADE_DATA_POSSE,NR_TITULO_ELEITORAL_CANDIDATO,CD_GENERO,DS_GENERO,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,VR_DESPESA_MAX_CAMPANHA,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,ST_REELEICAO,ST_DECLARAR_BENS,NR_PROTOCOLO_CANDIDATURA,NR_PROCESSO,CD_SITUACAO_CANDIDATO_PLEITO,DS_SITUACAO_CANDIDATO_PLEITO,CD_SITUACAO_CANDIDATO_URNA,DS_SITUACAO_CANDIDATO_URNA,ST_CANDIDATO_INSERIDO_URNA
0,23/05/2021,09:04:58,2018,2,ELEIÇÃO ORDINÁRIA,1,297,Eleições Gerais Estaduais 2018,07/10/2018,ESTADUAL,PE,PE,PERNAMBUCO,6,DEPUTADO FEDERAL,170000617438,5153,NIVALDO FELIPE DE LIRA,NIVALDO ASA BRANCA,#NULO#,12418226468,PATRI51ELECOES@HOTMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,51,PATRIOTA,PATRIOTA,170000050462,PARTIDO ISOLADO,PATRIOTA,1,BRASILEIRA NATA,PE,-3,RECIFE,26/07/1954,64.00,26913040868,2,MASCULINO,4,ENSINO FUNDAMENTAL COMPLETO,3,CASADO(A),3,PARDA,537,MOTORISTA PARTICULAR,2500000,5,SUPLENTE,N,N,-1,6012821720186170000,2,DEFERIDO,2,DEFERIDO,SIM
1,23/05/2021,09:04:58,2018,2,ELEIÇÃO ORDINÁRIA,1,297,Eleições Gerais Estaduais 2018,07/10/2018,ESTADUAL,MG,MG,MINAS GERAIS,6,DEPUTADO FEDERAL,130000610112,5100,ELTON GERALDO TAVARES,SARGENTO ELTON,#NULO#,87709732615,VEREADORSARGENTOELTON@GMAIL.COM,12,APTO,2,DEFERIDO,COLIGAÇÃO,51,PATRIOTA,PATRIOTA,130000050269,RENOVAÇÃO,PATRIOTA / PTC / PMB,1,BRASILEIRA NATA,MG,-3,DIVINOPOLIS,25/03/1972,46.00,87599010256,2,MASCULINO,7,SUPERIOR INCOMPLETO,3,CASADO(A),1,BRANCA,278,VEREADOR,2500000,5,SUPLENTE,N,S,-1,6007955820186130000,2,DEFERIDO,2,DEFERIDO,SIM
2,23/05/2021,09:04:58,2018,2,ELEIÇÃO ORDINÁRIA,1,297,Eleições Gerais Estaduais 2018,07/10/2018,ESTADUAL,PR,PR,PARANÁ,7,DEPUTADO ESTADUAL,160000609957,18888,JULIANA BARBOZA SYDOR,JULIANA SYDOR,#NULO#,98057553987,JULIANA.SYDOR@GMAIL.COM,12,APTO,2,DEFERIDO,COLIGAÇÃO,18,REDE,REDE SUSTENTABILIDADE,160000050264,Coligação do bem e da verdade para mudar o Paraná,REDE / DC / PPL,1,BRASILEIRA NATA,PR,-3,PATO BRANCO,17/11/1976,42.00,63046420639,4,FEMININO,8,SUPERIOR COMPLETO,3,CASADO(A),3,PARDA,125,ADMINISTRADOR,1000000,5,SUPLENTE,N,S,-1,6007775320186160000,2,DEFERIDO,2,DEFERIDO,SIM
3,23/05/2021,09:04:58,2018,2,ELEIÇÃO ORDINÁRIA,1,297,Eleições Gerais Estaduais 2018,07/10/2018,ESTADUAL,RJ,RJ,RIO DE JANEIRO,7,DEPUTADO ESTADUAL,190000623237,18008,ANDRÉ LUÍS CANTUÁRIA CARDOSO OLIVEIRA,PROFESSOR ANDRE CANTUARIA,#NULO#,03331311774,VTATSCH.ADV@GMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,18,REDE,REDE SUSTENTABILIDADE,190000050621,PARTIDO ISOLADO,REDE,1,BRASILEIRA NATA,RJ,-3,NOVA IGUAÇU,07/12/1971,47.00,80114020345,2,MASCULINO,7,SUPERIOR INCOMPLETO,1,SOLTEIRO(A),2,PRETA,142,PROFESSOR DE ENSINO SUPERIOR,1000000,4,NÃO ELEITO,N,S,-1,6034685620186190000,2,DEFERIDO,2,DEFERIDO,SIM
4,23/05/2021,09:04:58,2018,2,ELEIÇÃO ORDINÁRIA,1,297,Eleições Gerais Estaduais 2018,07/10/2018,ESTADUAL,AP,AP,AMAPÁ,7,DEPUTADO ESTADUAL,30000603080,17890,FERNANDO DA SILVA PEDROSO,FERNANDO PEDROSO,#NULO#,41570456291,RCA.SHARON@HOTMAIL.COM,12,APTO,2,DEFERIDO,COLIGAÇÃO,17,PSL,PARTIDO SOCIAL LIBERAL,30000050088,UNIDOS PELO AMAPA,PPS / PSL,1,BRASILEIRA NATA,AP,-3,SERRA DO NAVIO,12/11/1972,46.00,1457972577,2,MASCULINO,6,ENSINO MÉDIO COMPLETO,3,CASADO(A),3,PARDA,703,ELETRICISTA E ASSEMELHADOS,1000000,5,SUPLENTE,N,S,-1,6002020820186030000,2,DEFERIDO,2,DEFERIDO,SIM

In [35]:
df_2018.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'NR_CPF_CANDIDATO', 'NM_EMAIL',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND', 'TP_AGREMIACAO',
       'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO', 'SQ_COLIGACAO',
       'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO', 'CD_NACIONALIDADE',
       'DS_NACIONALIDADE', 'SG_UF_NASCIMENTO', 'CD_MUNICIPIO_NASCIMENTO',
       'NM_MUNICIPIO_NASCIMENTO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE',
       'NR_TITULO_ELEITORAL_CANDIDATO', 'CD_GENERO', 'DS_GENERO',
       'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO', 'CD_ESTADO_CIVIL',
       'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA', 'CD_OCUPACAO',
       'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA', 'CD_SIT_TOT_TURNO',
       'DS_SIT_TOT_TURNO', 'ST_REELEICAO', 'ST_DECLARAR_BENS',
       'NR_PROTOCOLO_CANDIDATURA', 'NR_PROCESSO',
       'CD_SITUACAO_CANDIDATO_PLEITO', 'DS_SITUACAO_CANDIDATO_PLEITO',
       'CD_SITUACAO_CANDIDATO_URNA', 'DS_SITUACAO_CANDIDATO_URNA',
       'ST_CANDIDATO_INSERIDO_URNA'],
      dtype='object')

### Vagas disponíveis para deputados estaduais por estado em 2018

Dados de vagas obtidos em: https://www.tse.jus.br/eleicoes/estatisticas/estatisticas-eleitorais

Para acessá-los basta selecionar quais os dados de interesse e fazer o download do arquivo na página tabelas detalhadas abaixo do título CANDIDATOS(AS) POR VAGA.

Vagas para deputado estadual por estado: 

“O número de Deputados à Assembleia Legislativa corresponderá ao triplo da representação do Estado na Câmara dos Deputados e, atingido o número de trinta e seis, será acrescido de tantos quantos forem os Deputados Federais acima de doze”, diz o artigo 27 da Constituição federal.

In [36]:
df_vagas_2018 = pd.read_csv('relacao_vaga_2018.csv', sep=';', encoding='latin1', low_memory=False, usecols=['UF','Cargo', 'Quantitativo', 'Vaga'])

df_deputados_estaduais_2018 = df_vagas_2018[df_vagas_2018['Cargo'] == 'Deputado Estadual']

df_deputados_estaduais_2018 = df_deputados_estaduais_2018.rename(columns={'UF': 'SG_UF', 'Vaga': 'VAGAS'});

In [37]:
df_deputados_estaduais_2018.head(10)

    SG_UF              Cargo  Quantitativo  VAGAS
110    AC  Deputado Estadual           471     24
111    AL  Deputado Estadual           336     27
112    AM  Deputado Estadual           657     24
113    AP  Deputado Estadual           495     24
114    BA  Deputado Estadual           643     63
115    CE  Deputado Estadual           597     46
116    ES  Deputado Estadual           614     30
117    GO  Deputado Estadual           907     41
118    MA  Deputado Estadual           535     42
119    MG  Deputado Estadual          1382     77

### Candidatos a deputados estaduais em 2018

Abaixo estão as coligações presentes em cada estado e a quantidade de candidaturas por gênero em cada coligação, além da quantidade de candidaturas por gênero representadas por partidos isolados:

### Deputados estaduais com coligação

Respostas para o campo de 'DS_GENERO':

In [38]:
df_2018['DS_GENERO'].unique()

array(['MASCULINO', 'FEMININO', 'NÃO DIVULGÁVEL'], dtype=object)

Gênero Feminino

In [39]:
df_deputado_estadual_com_coligacao_genero_feminino_2018 = df_2018[
    (df_2018['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2018['DS_GENERO'] == 'FEMININO') &
    (df_2018['TP_AGREMIACAO'] == 'COLIGAÇÃO') &
    (df_2018['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()

In [40]:
df_deputado_estadual_com_coligacao_genero_feminino_2018 = df_deputado_estadual_com_coligacao_genero_feminino_2018.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [41]:
df_deputado_estadual_com_coligacao_genero_feminino_2018.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_FEMININO
0,AC,ACRE,10000050007,"FRENTE - PSOL, PV, PRP E PPL",13
1,AC,ACRE,10000050011,Muda Acre de Verdade,12
2,AC,ACRE,10000050028,FRENTE POPULAR REPUBLICANA SOCIAL,10
3,AC,ACRE,10000050109,FORÇA DA UNIÃO FPA III,9
4,AC,ACRE,10000050189,COLIGAÇÃO FRENTE TRABALHISTA CRISTÃ,10

Gênero Masculino

In [42]:
df_deputado_estadual_com_coligacao_genero_masculino_2018 = df_2018[
    (df_2018['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2018['DS_GENERO'] == 'MASCULINO') &
    (df_2018['TP_AGREMIACAO'] == 'COLIGAÇÃO') &
    (df_2018['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()

In [43]:
df_deputado_estadual_com_coligacao_genero_masculino_2018 = df_deputado_estadual_com_coligacao_genero_masculino_2018.rename(columns={'DS_GENERO':'GENERO_MASCULINO'});

In [44]:
df_deputado_estadual_com_coligacao_genero_masculino_2018.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_MASCULINO
0,AC,ACRE,10000050007,"FRENTE - PSOL, PV, PRP E PPL",27
1,AC,ACRE,10000050011,Muda Acre de Verdade,29
2,AC,ACRE,10000050028,FRENTE POPULAR REPUBLICANA SOCIAL,24
3,AC,ACRE,10000050109,FORÇA DA UNIÃO FPA III,21
4,AC,ACRE,10000050189,COLIGAÇÃO FRENTE TRABALHISTA CRISTÃ,24

Não há nenhum deputado estadual registrado como genêro não divulgável

In [45]:
df_2018[df_2018['DS_GENERO'] == 'NÃO DIVULGÁVEL']

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_CARGO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,NM_URNA_CANDIDATO,NM_SOCIAL_CANDIDATO,NR_CPF_CANDIDATO,NM_EMAIL,CD_SITUACAO_CANDIDATURA,DS_SITUACAO_CANDIDATURA,CD_DETALHE_SITUACAO_CAND,DS_DETALHE_SITUACAO_CAND,TP_AGREMIACAO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,CD_NACIONALIDADE,DS_NACIONALIDADE,SG_UF_NASCIMENTO,CD_MUNICIPIO_NASCIMENTO,NM_MUNICIPIO_NASCIMENTO,DT_NASCIMENTO,NR_IDADE_DATA_POSSE,NR_TITULO_ELEITORAL_CANDIDATO,CD_GENERO,DS_GENERO,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,VR_DESPESA_MAX_CAMPANHA,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,ST_REELEICAO,ST_DECLARAR_BENS,NR_PROTOCOLO_CANDIDATURA,NR_PROCESSO,CD_SITUACAO_CANDIDATO_PLEITO,DS_SITUACAO_CANDIDATO_PLEITO,CD_SITUACAO_CANDIDATO_URNA,DS_SITUACAO_CANDIDATO_URNA,ST_CANDIDATO_INSERIDO_URNA
20045,23/05/2021,09:05:53,2018,2,ELEIÇÃO ORDINÁRIA,1,297,Eleições Gerais Estaduais 2018,07/10/2018,ESTADUAL,DF,DF,DISTRITO FEDERAL,5,SENADOR,70000602381,300,PAULO ROBERTO ROQUE ANTONIO KHOURI,PAULO ROQUE,NÃO DIVULGÁVEL,000000000-4,NÃO DIVULGÁVEL,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,30,NOVO,PARTIDO NOVO,70000050065,PARTIDO ISOLADO,NOVO,-4,NÃO DIVULGÁVEL,Não divulgável,-3,NÃO DIVULGÁVEL,NaN,nan,-4,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,NÃO DIVULGÁVEL,-4,4,NÃO ELEITO,Não divulgável,Não divulgável,-1,6004575220186070000,2,DEFERIDO,2,DEFERIDO,SIM

Colocando os resultados numa mesma tabela:

In [46]:
df_deputado_estadual_com_coligacao_por_genero_2018 = pd.merge(df_deputado_estadual_com_coligacao_genero_feminino_2018, df_deputado_estadual_com_coligacao_genero_masculino_2018[['SQ_COLIGACAO', 'GENERO_MASCULINO']], on = 'SQ_COLIGACAO', how = 'outer')

In [47]:
df_deputado_estadual_com_coligacao_por_genero_2018.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_FEMININO,GENERO_MASCULINO
0,AC,ACRE,10000050007,"FRENTE - PSOL, PV, PRP E PPL",13,27
1,AC,ACRE,10000050011,Muda Acre de Verdade,12,29
2,AC,ACRE,10000050028,FRENTE POPULAR REPUBLICANA SOCIAL,10,24
3,AC,ACRE,10000050109,FORÇA DA UNIÃO FPA III,9,21
4,AC,ACRE,10000050189,COLIGAÇÃO FRENTE TRABALHISTA CRISTÃ,10,24

Total de candidatos por coligação por município:

In [48]:
df_deputado_estadual_com_coligacao_por_genero_2018['TOTAL'] = df_deputado_estadual_com_coligacao_por_genero_2018['GENERO_FEMININO'] + df_deputado_estadual_com_coligacao_por_genero_2018['GENERO_MASCULINO']

Porcentagem de candidatos por gênero

In [49]:
df_deputado_estadual_com_coligacao_por_genero_2018['PERC_FEM'] = (df_deputado_estadual_com_coligacao_por_genero_2018['GENERO_FEMININO']/df_deputado_estadual_com_coligacao_por_genero_2018['TOTAL'])*100
df_deputado_estadual_com_coligacao_por_genero_2018['PERC_MASC'] = (df_deputado_estadual_com_coligacao_por_genero_2018['GENERO_MASCULINO']/df_deputado_estadual_com_coligacao_por_genero_2018['TOTAL'])*100

In [50]:
df_deputado_estadual_com_coligacao_por_genero_2018 = pd.merge(df_deputado_estadual_com_coligacao_por_genero_2018, df_deputados_estaduais_2018[['SG_UF', 'VAGAS']] , on = 'SG_UF')

In [51]:
df_deputado_estadual_com_coligacao_por_genero_2018['PERCENT_OCUPADO'] = (df_deputado_estadual_com_coligacao_por_genero_2018['TOTAL']/df_deputado_estadual_com_coligacao_por_genero_2018['VAGAS'])*100

In [52]:
df_deputado_estadual_com_coligacao_por_genero_2018.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NM_COLIGACAO,GENERO_FEMININO,GENERO_MASCULINO,TOTAL,PERC_FEM,PERC_MASC,VAGAS,PERCENT_OCUPADO
0,AC,ACRE,10000050007,"FRENTE - PSOL, PV, PRP E PPL",13,27,40,32.50,67.50,24,166.67
1,AC,ACRE,10000050011,Muda Acre de Verdade,12,29,41,29.27,70.73,24,170.83
2,AC,ACRE,10000050028,FRENTE POPULAR REPUBLICANA SOCIAL,10,24,34,29.41,70.59,24,141.67
3,AC,ACRE,10000050109,FORÇA DA UNIÃO FPA III,9,21,30,30.00,70.00,24,125.00
4,AC,ACRE,10000050189,COLIGAÇÃO FRENTE TRABALHISTA CRISTÃ,10,24,34,29.41,70.59,24,141.67

### Deputados estaduais sem coligação

In [53]:
df_deputado_estadual_sem_coligacoes_genero_feminino_2018 = df_2018[
    (df_2018['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2018['DS_GENERO'] == 'FEMININO') &
    (df_2018['TP_AGREMIACAO'] == 'PARTIDO ISOLADO') &
    (df_2018['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO', 'NR_PARTIDO', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()
df_deputado_estadual_sem_coligacoes_genero_feminino_2018 = df_deputado_estadual_sem_coligacoes_genero_feminino_2018.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [54]:
df_deputado_estadual_sem_coligacoes_genero_feminino_2018.head()

  SG_UF NM_UE  SQ_COLIGACAO  NR_PARTIDO     SG_PARTIDO  GENERO_FEMININO
0    AC  ACRE   10000050036          14            PTB                9
1    AC  ACRE   10000050039          18           REDE                3
2    AC  ACRE   10000050063          12            PDT                9
3    AC  ACRE   10000050085          77  SOLIDARIEDADE                8
4    AC  ACRE   10000050139          40            PSB               12

In [55]:
df_deputado_estadual_sem_coligacoes_genero_masculino_2018 = df_2018[
    (df_2018['DS_CARGO'] == 'DEPUTADO ESTADUAL') &
    (df_2018['DS_GENERO'] == 'MASCULINO') &
    (df_2018['TP_AGREMIACAO'] == 'PARTIDO ISOLADO') &
    (df_2018['DS_SITUACAO_CANDIDATURA'] == 'APTO')
].groupby(['SG_UF','NM_UE', 'SQ_COLIGACAO','NR_PARTIDO', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()
df_deputado_estadual_sem_coligacoes_genero_masculino_2018 = df_deputado_estadual_sem_coligacoes_genero_masculino_2018.rename(columns={'DS_GENERO':'GENERO_MASCULINO'});

In [56]:
df_deputado_estadual_sem_coligacoes_genero_masculino_2018.head()

  SG_UF NM_UE  SQ_COLIGACAO  NR_PARTIDO     SG_PARTIDO  GENERO_MASCULINO
0    AC  ACRE   10000050036          14            PTB                18
1    AC  ACRE   10000050039          18           REDE                 7
2    AC  ACRE   10000050063          12            PDT                18
3    AC  ACRE   10000050085          77  SOLIDARIEDADE                15
4    AC  ACRE   10000050139          40            PSB                20

In [57]:
df_deputado_estadual_sem_coligacoes_por_genero_2018 = pd.merge(df_deputado_estadual_sem_coligacoes_genero_feminino_2018, df_deputado_estadual_sem_coligacoes_genero_masculino_2018[['SQ_COLIGACAO', 'GENERO_MASCULINO']], on = 'SQ_COLIGACAO', how = 'outer')
df_deputado_estadual_sem_coligacoes_por_genero_2018 = df_deputado_estadual_sem_coligacoes_por_genero_2018.fillna(0)

In [58]:
df_deputado_estadual_sem_coligacoes_por_genero_2018.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NR_PARTIDO,SG_PARTIDO,GENERO_FEMININO,GENERO_MASCULINO
0,AC,ACRE,10000050036,14.00,PTB,9.00,18.00
1,AC,ACRE,10000050039,18.00,REDE,3.00,7.00
2,AC,ACRE,10000050063,12.00,PDT,9.00,18.00
3,AC,ACRE,10000050085,77.00,SOLIDARIEDADE,8.00,15.00
4,AC,ACRE,10000050139,40.00,PSB,12.00,20.00

In [59]:
df_deputado_estadual_sem_coligacoes_por_genero_2018['TOTAL'] = df_deputado_estadual_sem_coligacoes_por_genero_2018['GENERO_FEMININO'] + df_deputado_estadual_sem_coligacoes_por_genero_2018['GENERO_MASCULINO']
df_deputado_estadual_sem_coligacoes_por_genero_2018['PERC_FEM'] = (df_deputado_estadual_sem_coligacoes_por_genero_2018['GENERO_FEMININO']/df_deputado_estadual_sem_coligacoes_por_genero_2018['TOTAL'])*100
df_deputado_estadual_sem_coligacoes_por_genero_2018['PERC_MASC'] = (df_deputado_estadual_sem_coligacoes_por_genero_2018['GENERO_MASCULINO']/df_deputado_estadual_sem_coligacoes_por_genero_2018['TOTAL'])*100

In [60]:
df_deputado_estadual_sem_coligacoes_por_genero_2018 = pd.merge(df_deputado_estadual_sem_coligacoes_por_genero_2018, df_deputados_estaduais_2018[['SG_UF', 'VAGAS']] , on = 'SG_UF')

In [61]:
df_deputado_estadual_sem_coligacoes_por_genero_2018['PERCENT_OCUPADO'] = (df_deputado_estadual_sem_coligacoes_por_genero_2018['TOTAL']/df_deputado_estadual_sem_coligacoes_por_genero_2018['VAGAS'])*100

In [62]:
df_deputado_estadual_sem_coligacoes_por_genero_2018.head()

,SG_UF,NM_UE,SQ_COLIGACAO,NR_PARTIDO,SG_PARTIDO,GENERO_FEMININO,GENERO_MASCULINO,TOTAL,PERC_FEM,PERC_MASC,VAGAS,PERCENT_OCUPADO
0,AC,ACRE,10000050036,14.00,PTB,9.00,18.00,27.00,33.33,66.67,24,112.50
1,AC,ACRE,10000050039,18.00,REDE,3.00,7.00,10.00,30.00,70.00,24,41.67
2,AC,ACRE,10000050063,12.00,PDT,9.00,18.00,27.00,33.33,66.67,24,112.50
3,AC,ACRE,10000050085,77.00,SOLIDARIEDADE,8.00,15.00,23.00,34.78,65.22,24,95.83
4,AC,ACRE,10000050139,40.00,PSB,12.00,20.00,32.00,37.50,62.50,24,133.33