In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import unidecode
import time

from openpyxl import load_workbook
#import basedosdados as bd

pd.options.display.float_format = '{:.2f}'.format
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Queremos as seguintes colunas:

* MUNICIPIO 
* NOME_PARTIDO
* NOHOMENS 
* NOMULHERES 
* TOTAL 
* PERCENTDASVAGASDISPONIVEIS 
* NUMERODEVAGASDISPONIVEIS

# Vereadores

## 2016 (com e sem coligação)

In [2]:
path = 'consulta_cand_2016/consulta_cand_2016_BRASIL.csv'
df_2016 = pd.read_csv(path, sep=';', encoding='latin1', low_memory=False, decimal=',')

df_2016.head()

FileNotFoundError: [Errno 2] No such file or directory: 'consulta_cand_2016/consulta_cand_2016_BRASIL.csv'

In [3]:
df_2016.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'NR_CPF_CANDIDATO', 'NM_EMAIL',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND', 'TP_AGREMIACAO',
       'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO', 'SQ_COLIGACAO',
       'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO', 'CD_NACIONALIDADE',
       'DS_NACIONALIDADE', 'SG_UF_NASCIMENTO', 'CD_MUNICIPIO_NASCIMENTO',
       'NM_MUNICIPIO_NASCIMENTO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE',
       'NR_TITULO_ELEITORAL_CANDIDATO', 'CD_GENERO', 'DS_GENERO',
       'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO', 'CD_ESTADO_CIVIL',
       'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA', 'CD_OCUPACAO',
       'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA', 'CD_SIT_TOT_TURNO',
       'DS_SIT_TOT_TURNO', 'ST_REELEICAO', 'ST_DECLARAR_BENS',
       'NR_PROTOCOLO_CANDIDATURA', 'NR_PROCESSO',
       'CD_SITUACAO_CANDIDATO_PLEITO', 'DS_SITUACAO_CANDIDATO_PLEITO',
       'CD_SITUACAO_CANDIDATO_URNA', 'DS_SITUACAO_CANDIDATO_URNA',
       'ST_CANDIDATO_INSERIDO_URNA'],
      dtype='object')

### Vagas disponíveis para vereador por município em 2016

A disposição das vagas se dá pela quantidade de habitantes do município, mas prevalece a lei orgância municipal.

In [4]:
df_vagas_2016 = pd.read_csv('relacao_vaga_2016.csv', sep=';', encoding='latin1', low_memory=False, usecols=['UF', 'Município', 'Cargo', 'Quantitativo', 'Vaga'])

df_vereador_2016 = df_vagas_2016[df_vagas_2016['Cargo'] == 'Vereador']

df_vereador_2016 = df_vereador_2016.rename(columns={'Município':'NM_UE', 'Vaga': 'VAGAS'});

In [5]:
df_vereador_2016.head(10)

       UF            NM_UE     Cargo  Quantitativo  VAGAS
11136  AC       ACRELÂNDIA  Vereador            91      9
11137  AC     ASSIS BRASIL  Vereador            53      9
11138  AC        BRASILÉIA  Vereador            82     11
11139  AC           BUJARI  Vereador            85      9
11140  AC         CAPIXABA  Vereador            80      9
11141  AC  CRUZEIRO DO SUL  Vereador           178     14
11142  AC   EPITACIOLÂNDIA  Vereador            80      9
11143  AC            FEIJÓ  Vereador            92     13
11144  AC           JORDÃO  Vereador            53      9
11145  AC      MÂNCIO LIMA  Vereador            97     11

### Candidatos a vereador em 2016

Abaixo estão as coligações presentes em cada município e a quantidade de candidaturas por gênero em cada coligação, além da quantidade de candidaturas por gênero representadas por partidos isolados:

### Vereadores com coligação

In [6]:
df_vereador_com_coligacao_genero_feminino_2016 = df_2016[
    (df_2016['DS_CARGO'] == 'VEREADOR') &
    (df_2016['DS_GENERO'] == 'FEMININO') &
    (df_2016['TP_AGREMIACAO'] == 'COLIGAÇÃO')
].groupby(['SG_UF','NM_UE', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()

In [7]:
df_vereador_com_coligacao_genero_feminino_2016 = df_vereador_com_coligacao_genero_feminino_2016.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [8]:
df_vereador_com_coligacao_genero_feminino_2016.head()

  SG_UF       NM_UE                     NM_COLIGACAO  GENERO_FEMININO
0    AC  ACRELÂNDIA  Juntos Com Coragem e Atitude II                3
1    AC  ACRELÂNDIA   Juntos com Coragem e Atitude I                5
2    AC  ACRELÂNDIA           PRODUZIR PARA EMPREGAR                6
3    AC  ACRELÂNDIA            UNIDOS POR ACRELANDIA                6
4    AC  ACRELÂNDIA  VAMOS JUNTOS RENOVAR ACRELÂNDIA                3

In [9]:
df_vereador_com_coligacao_genero_masculino_2016 = df_2016[
    (df_2016['DS_CARGO'] == 'VEREADOR') &
    (df_2016['DS_GENERO'] == 'MASCULINO') &
    (df_2016['TP_AGREMIACAO'] == 'COLIGAÇÃO')
].groupby(['SG_UF','NM_UE', 'NM_COLIGACAO'], as_index = False)['DS_GENERO'].count()

In [10]:
df_vereador_com_coligacao_genero_masculino_2016.head()

  SG_UF       NM_UE                     NM_COLIGACAO  DS_GENERO
0    AC  ACRELÂNDIA  Juntos Com Coragem e Atitude II          6
1    AC  ACRELÂNDIA   Juntos com Coragem e Atitude I         12
2    AC  ACRELÂNDIA           PRODUZIR PARA EMPREGAR         12
3    AC  ACRELÂNDIA            UNIDOS POR ACRELANDIA         13
4    AC  ACRELÂNDIA  VAMOS JUNTOS RENOVAR ACRELÂNDIA          7

In [11]:
df_vereador_com_coligacao_genero_feminino_2016['GENERO_MASCULINO'] = df_vereador_com_coligacao_genero_masculino_2016['DS_GENERO']

In [12]:
df_vereador_com_coligacao_genero_feminino_2016['TOTAL'] = df_vereador_com_coligacao_genero_feminino_2016['GENERO_FEMININO'] + df_vereador_com_coligacao_genero_feminino_2016['GENERO_MASCULINO']

In [13]:
df_vereador_com_coligacao_por_genero_2016 = pd.merge(df_vereador_com_coligacao_genero_feminino_2016, df_vereador_2016[['NM_UE', 'VAGAS']] , on = 'NM_UE')

In [14]:
df_vereador_com_coligacao_por_genero_2016.head()

,SG_UF,NM_UE,NM_COLIGACAO,GENERO_FEMININO,GENERO_MASCULINO,TOTAL,VAGAS
0,AC,ACRELÂNDIA,Juntos Com Coragem e Atitude II,3,6,9,9
1,AC,ACRELÂNDIA,Juntos com Coragem e Atitude I,5,12,17,9
2,AC,ACRELÂNDIA,PRODUZIR PARA EMPREGAR,6,12,18,9
3,AC,ACRELÂNDIA,UNIDOS POR ACRELANDIA,6,13,19,9
4,AC,ACRELÂNDIA,VAMOS JUNTOS RENOVAR ACRELÂNDIA,3,7,10,9

### Vereadores sem coligação

In [15]:
df_vereador_sem_coligacoes_genero_feminino_2016 = df_2016[
    (df_2016['DS_CARGO'] == 'VEREADOR') &
    (df_2016['DS_GENERO'] == 'FEMININO') &
    (df_2016['TP_AGREMIACAO'] == 'PARTIDO ISOLADO')
].groupby(['SG_UF','NM_UE', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()

In [16]:
df_vereador_sem_coligacoes_genero_feminino_2016.head()

  SG_UF           NM_UE SG_PARTIDO  DS_GENERO
0    AC      ACRELÂNDIA       PSDB          3
1    AC      ACRELÂNDIA         PT          3
2    AC    ASSIS BRASIL    PC do B          4
3    AC          BUJARI         PP          5
4    AC  EPITACIOLÂNDIA        DEM          1

In [17]:
df_vereador_sem_coligacoes_genero_masculino_2016 = df_2016[
    (df_2016['DS_CARGO'] == 'VEREADOR') &
    (df_2016['DS_GENERO'] == 'MASCULINO') &
    (df_2016['TP_AGREMIACAO'] == 'PARTIDO ISOLADO')
].groupby(['SG_UF','NM_UE', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()

In [18]:
df_vereador_sem_coligacoes_genero_masculino_2016.head()

  SG_UF         NM_UE SG_PARTIDO  DS_GENERO
0    AC    ACRELÂNDIA       PSDB          7
1    AC    ACRELÂNDIA         PT          5
2    AC  ASSIS BRASIL    PC do B          8
3    AC        BUJARI         PP          9
4    AC        JORDÃO         PV          1

In [19]:
df_vereador_sem_coligacoes_genero_feminino_2016 = df_vereador_sem_coligacoes_genero_feminino_2016.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [20]:
df_vereador_sem_coligacoes_genero_feminino_2016['GENERO_MASCULINO'] = df_vereador_sem_coligacoes_genero_masculino_2016['DS_GENERO']

In [21]:
df_vereador_sem_coligacoes_genero_feminino_2016['TOTAL'] = df_vereador_sem_coligacoes_genero_feminino_2016['GENERO_FEMININO'] + df_vereador_sem_coligacoes_genero_feminino_2016['GENERO_MASCULINO']

In [22]:
df_vereador_sem_coligacoes_por_genero_2016 = pd.merge(df_vereador_sem_coligacoes_genero_feminino_2016, df_vereador_2016[['NM_UE', 'VAGAS']] , on = 'NM_UE')

In [23]:
df_vereador_sem_coligacoes_por_genero_2016.head()

,SG_UF,NM_UE,SG_PARTIDO,GENERO_FEMININO,GENERO_MASCULINO,TOTAL,VAGAS
0,AC,ACRELÂNDIA,PSDB,3,7,10,9
1,AC,ACRELÂNDIA,PT,3,5,8,9
2,AC,ASSIS BRASIL,PC do B,4,8,12,9
3,AC,BUJARI,PP,5,9,14,9
4,AC,EPITACIOLÂNDIA,DEM,1,1,2,9

## 2020 (sem coligação)

"Pela primeira vez, partidos políticos não poderão se coligar para concorrerem ao cargo de vereador, podendo apresentar pedidos somente de forma isolada".  A nova regra foi fixada pela Emenda Constitucional nº 97/2017.

https://www.tse.jus.br/imprensa/noticias-tse/2020/Novembro/eleicoes-2020-58-208-vagas-de-vereadores-estarao-em-disputa-neste-domingo-15

### Vagas disponíveis para vereador por município

In [24]:
df_vagas_2020 = pd.read_csv('relacao_vaga_2020.csv', sep=';', encoding='latin1', low_memory=False, usecols=['UF', 'Município', 'Cargo', 'Quantitativo', 'Vaga'])

df_vereador_2020 = df_vagas_2020[df_vagas_2020['Cargo'] == 'Vereador']

df_vereador_2020 = df_vereador_2020.rename(columns={'Município':'NM_UE', 'Vaga':'VAGAS'});

In [25]:
df_vereador_2020.head(10)

       UF            NM_UE     Cargo  Quantitativo  VAGAS
11136  AC       ACRELÂNDIA  Vereador            79      9
11137  AC     ASSIS BRASIL  Vereador            85      9
11138  AC        BRASILÉIA  Vereador           136     11
11139  AC           BUJARI  Vereador           130      9
11140  AC         CAPIXABA  Vereador           104      9
11141  AC  CRUZEIRO DO SUL  Vereador           209     14
11142  AC   EPITACIOLÂNDIA  Vereador           127      9
11143  AC            FEIJÓ  Vereador           141     13
11144  AC           JORDÃO  Vereador            74      9
11145  AC      MÂNCIO LIMA  Vereador           125     11

In [26]:
path = 'consulta_cand_2020/consulta_cand_2020_BRASIL.csv'
df_2020 = pd.read_csv(path, sep=';', encoding='latin1', low_memory=False, decimal=',')

df_2020.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,CD_TIPO_ELEICAO,NM_TIPO_ELEICAO,NR_TURNO,CD_ELEICAO,DS_ELEICAO,DT_ELEICAO,TP_ABRANGENCIA,SG_UF,SG_UE,NM_UE,CD_CARGO,DS_CARGO,SQ_CANDIDATO,NR_CANDIDATO,NM_CANDIDATO,NM_URNA_CANDIDATO,NM_SOCIAL_CANDIDATO,NR_CPF_CANDIDATO,NM_EMAIL,CD_SITUACAO_CANDIDATURA,DS_SITUACAO_CANDIDATURA,CD_DETALHE_SITUACAO_CAND,DS_DETALHE_SITUACAO_CAND,TP_AGREMIACAO,NR_PARTIDO,SG_PARTIDO,NM_PARTIDO,SQ_COLIGACAO,NM_COLIGACAO,DS_COMPOSICAO_COLIGACAO,CD_NACIONALIDADE,DS_NACIONALIDADE,SG_UF_NASCIMENTO,CD_MUNICIPIO_NASCIMENTO,NM_MUNICIPIO_NASCIMENTO,DT_NASCIMENTO,NR_IDADE_DATA_POSSE,NR_TITULO_ELEITORAL_CANDIDATO,CD_GENERO,DS_GENERO,CD_GRAU_INSTRUCAO,DS_GRAU_INSTRUCAO,CD_ESTADO_CIVIL,DS_ESTADO_CIVIL,CD_COR_RACA,DS_COR_RACA,CD_OCUPACAO,DS_OCUPACAO,VR_DESPESA_MAX_CAMPANHA,CD_SIT_TOT_TURNO,DS_SIT_TOT_TURNO,ST_REELEICAO,ST_DECLARAR_BENS,NR_PROTOCOLO_CANDIDATURA,NR_PROCESSO,CD_SITUACAO_CANDIDATO_PLEITO,DS_SITUACAO_CANDIDATO_PLEITO,CD_SITUACAO_CANDIDATO_URNA,DS_SITUACAO_CANDIDATO_URNA,ST_CANDIDATO_INSERIDO_URNA
0,29/05/2021,12:19:11,2020,2,ELEIÇÃO ORDINÁRIA,1,426,Eleições Municipais 2020,15/11/2020,MUNICIPAL,SP,65099,ILHABELA,13,VEREADOR,250001078745,70565,JOSE PEREIRA BRANDÃO,ZÉ BRANDÃO,#NULO#,5400594808,ILHAVIVA2020@GMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,70,AVANTE,AVANTE,250000130531,PARTIDO ISOLADO,AVANTE,1,BRASILEIRA NATA,MG,-3,GRÃO MOGOL,08/03/1958,62,47636980108,2,MASCULINO,6,ENSINO MÉDIO COMPLETO,9,DIVORCIADO(A),3,PARDA,709,TRABALHADOR DE CONSTRUÇÃO CIVIL,12307.75,5,SUPLENTE,N,S,-1,6005873520206260132,2,DEFERIDO,2,DEFERIDO,SIM
1,29/05/2021,12:19:11,2020,2,ELEIÇÃO ORDINÁRIA,1,426,Eleições Municipais 2020,15/11/2020,MUNICIPAL,BA,37567,NOVA FÁTIMA,13,VEREADOR,50000941067,11135,ERIVANIA ARAUJO DA SILVA,KAL ARAUJO,#NULO#,3279617596,UNIDOSPORNOVAFATIMA@GMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,11,PP,PROGRESSISTAS,50000108688,PARTIDO ISOLADO,PP,1,BRASILEIRA NATA,BA,-3,RIACHÃO DO JACUÍPE,01/04/1986,34,116352710507,4,FEMININO,7,SUPERIOR INCOMPLETO,9,DIVORCIADO(A),3,PARDA,254,VIGILANTE,12307.75,5,SUPLENTE,N,S,-1,6001862320206050196,2,DEFERIDO,2,DEFERIDO,SIM
2,29/05/2021,12:19:11,2020,2,ELEIÇÃO ORDINÁRIA,1,426,Eleições Municipais 2020,15/11/2020,MUNICIPAL,PB,19763,ALCANTIL,13,VEREADOR,150000859227,12112,ARLETE BARBOSA COSTA,ARLETE,#NULO#,26253330497,JOAO.RODRIGUES.SEGUNDO@OUTLOOK.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,12,PDT,PARTIDO DEMOCRÁTICO TRABALHISTA,150000093695,PARTIDO ISOLADO,PDT,1,BRASILEIRA NATA,PB,-3,BOQUEIRÃO,12/02/1959,61,11174261295,4,FEMININO,6,ENSINO MÉDIO COMPLETO,3,CASADO(A),3,PARDA,999,OUTROS,12307.75,5,SUPLENTE,N,S,-1,6001080220206150018,2,DEFERIDO,2,DEFERIDO,SIM
3,29/05/2021,12:19:11,2020,2,ELEIÇÃO ORDINÁRIA,1,426,Eleições Municipais 2020,15/11/2020,MUNICIPAL,SP,70971,SÃO JOSÉ DO RIO PRETO,13,VEREADOR,250001178195,11123,DAVID MARCELINO CARDOZO,DAVID CARDOZO,#NULO#,6451512893,DAVI.CARDOZO@HOTMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,11,PP,PROGRESSISTAS,250000145024,PARTIDO ISOLADO,PP,1,BRASILEIRA NATA,SP,-3,SÃO JOSÉ DO RIO PRETO,07/05/1965,55,58495610141,2,MASCULINO,8,SUPERIOR COMPLETO,3,CASADO(A),1,BRANCA,133,SOCIÓLOGO,113318.61,5,SUPLENTE,N,S,-1,6004308320206260125,2,DEFERIDO,2,DEFERIDO,SIM
4,29/05/2021,12:19:11,2020,2,ELEIÇÃO ORDINÁRIA,1,426,Eleições Municipais 2020,15/11/2020,MUNICIPAL,SP,71072,SÃO PAULO,13,VEREADOR,250001159238,90333,MANOEL MILANEZ DA SILVA FILHO,MILANEZ,#NULO#,84883987434,MILANEZEFMANO@GMAIL.COM,12,APTO,2,DEFERIDO,PARTIDO ISOLADO,90,PROS,PARTIDO REPUBLICANO DA ORDEM SOCIAL,250000140997,PARTIDO ISOLADO,PROS,1,BRASILEIRA NATA,SP,-3,SÃO PAULO,04/11/1973,47,40986080809,2,MASCULINO,6,ENSINO MÉDIO COMPLETO,1,SOLTEIRO(A),1,BRANCA,257,EMPRESÁRIO,3675197.12,4,NÃO ELEITO,N,N,-1,6019843720206260001,2,DEFERIDO,2,DEFERIDO,SIM

In [27]:
df_2020.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'NR_TURNO', 'CD_ELEICAO', 'DS_ELEICAO', 'DT_ELEICAO',
       'TP_ABRANGENCIA', 'SG_UF', 'SG_UE', 'NM_UE', 'CD_CARGO', 'DS_CARGO',
       'SQ_CANDIDATO', 'NR_CANDIDATO', 'NM_CANDIDATO', 'NM_URNA_CANDIDATO',
       'NM_SOCIAL_CANDIDATO', 'NR_CPF_CANDIDATO', 'NM_EMAIL',
       'CD_SITUACAO_CANDIDATURA', 'DS_SITUACAO_CANDIDATURA',
       'CD_DETALHE_SITUACAO_CAND', 'DS_DETALHE_SITUACAO_CAND', 'TP_AGREMIACAO',
       'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO', 'SQ_COLIGACAO',
       'NM_COLIGACAO', 'DS_COMPOSICAO_COLIGACAO', 'CD_NACIONALIDADE',
       'DS_NACIONALIDADE', 'SG_UF_NASCIMENTO', 'CD_MUNICIPIO_NASCIMENTO',
       'NM_MUNICIPIO_NASCIMENTO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE',
       'NR_TITULO_ELEITORAL_CANDIDATO', 'CD_GENERO', 'DS_GENERO',
       'CD_GRAU_INSTRUCAO', 'DS_GRAU_INSTRUCAO', 'CD_ESTADO_CIVIL',
       'DS_ESTADO_CIVIL', 'CD_COR_RACA', 'DS_COR_RACA', 'CD_OCUPACAO',
       'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA', 'CD_SIT_TOT_TURNO',
       'DS_SIT_TOT_TURNO', 'ST_REELEICAO', 'ST_DECLARAR_BENS',
       'NR_PROTOCOLO_CANDIDATURA', 'NR_PROCESSO',
       'CD_SITUACAO_CANDIDATO_PLEITO', 'DS_SITUACAO_CANDIDATO_PLEITO',
       'CD_SITUACAO_CANDIDATO_URNA', 'DS_SITUACAO_CANDIDATO_URNA',
       'ST_CANDIDATO_INSERIDO_URNA'],
      dtype='object')

In [28]:
df_vereador_sem_coligacoes_genero_feminino_2020 = df_2020[
    (df_2020['DS_CARGO'] == 'VEREADOR') &
    (df_2020['DS_GENERO'] == 'FEMININO')
].groupby(['SG_UF','NM_UE', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()

In [29]:
df_vereador_sem_coligacoes_genero_feminino_2020 = df_vereador_sem_coligacoes_genero_feminino_2020.rename(columns={'DS_GENERO':'GENERO_FEMININO'});

In [30]:
df_vereador_sem_coligacoes_genero_feminino_2020.head()

  SG_UF       NM_UE SG_PARTIDO  GENERO_FEMININO
0    AC  ACRELÂNDIA        DEM                1
1    AC  ACRELÂNDIA        MDB                4
2    AC  ACRELÂNDIA        PDT                1
3    AC  ACRELÂNDIA         PL                3
4    AC  ACRELÂNDIA         PP                5

In [31]:
df_vereador_sem_coligacoes_genero_masculino_2020 = df_2020[
    (df_2020['DS_CARGO'] == 'VEREADOR') &
    (df_2020['DS_GENERO'] == 'MASCULINO')
].groupby(['SG_UF','NM_UE', 'SG_PARTIDO'], as_index = False)['DS_GENERO'].count()

In [32]:
df_vereador_sem_coligacoes_genero_masculino_2020.head()

  SG_UF       NM_UE SG_PARTIDO  DS_GENERO
0    AC  ACRELÂNDIA        DEM          1
1    AC  ACRELÂNDIA        MDB          8
2    AC  ACRELÂNDIA        PDT          2
3    AC  ACRELÂNDIA         PL          6
4    AC  ACRELÂNDIA         PP          9

In [33]:
df_vereador_sem_coligacoes_genero_feminino_2020['GENERO_MASCULINO'] = df_vereador_sem_coligacoes_genero_masculino_2020['DS_GENERO']

In [34]:
df_vereador_sem_coligacoes_genero_feminino_2020['TOTAL'] = df_vereador_sem_coligacoes_genero_feminino_2020['GENERO_FEMININO'] + df_vereador_sem_coligacoes_genero_feminino_2020['GENERO_MASCULINO']

In [36]:
df_vereador_sem_coligacoes_por_genero_2020 = pd.merge(df_vereador_sem_coligacoes_genero_feminino_2020, df_vereador_2020[['NM_UE', 'VAGAS']] , on = 'NM_UE')

In [37]:
df_vereador_sem_coligacoes_por_genero_2020.head()

,SG_UF,NM_UE,SG_PARTIDO,GENERO_FEMININO,GENERO_MASCULINO,TOTAL,VAGAS
0,AC,ACRELÂNDIA,DEM,1,1,2,9
1,AC,ACRELÂNDIA,MDB,4,8,12,9
2,AC,ACRELÂNDIA,PDT,1,2,3,9
3,AC,ACRELÂNDIA,PL,3,6,9,9
4,AC,ACRELÂNDIA,PP,5,9,14,9